//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAuthor
    {
        public int Id_book { get; set; }
        public int Id_author { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Author Entity3 { get; set; }
    }
}
